### ISSUE TITLE
Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by lterlecki** [davetayls/space-invaders#1]
On clean Debian 9, only with nodejs i have an error:
/var/www/html/multiplayer# node server.js /var/www/html/multiplayer/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/var/www/html/multiplayer/node_modules/socket.io/lib/store.js:35:42)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/html/multiplayer/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:635:30)

/var/www/html/multiplayer# node -v
v8.9.1

**Comment by ShuhaoWang-AI** [comment]
Got the same error on node version 8.10.0
